apiVersion: v1
kind: Service
metadata:
  name: mock-pms
  labels:
    app.kubernetes.io/name: mock-pms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mock-pms
  ports:
    - name: http
      port: 3001
      targetPort: http
